### ISSUE TITLE
[AI] Mobs try to attack from far

### ISSUE THREAD

**Issue by Shameness** [NZNathan/Project-Survive#2]
<img width="140" alt="mobs-attack-from-far" src="https://user-images.githubusercontent.com/12902398/29389048-f7f9ba32-82b5-11e7-82d3-fab41d126516.PNG">

- Mobs are trying to attack from far.  
- Expected to come close melee range to attack. 
- Doesn't occur in starting area, happens one of the generated area type where 3 aggressive mob reside.  
- If confirmed might need to be fixed, else it is probably only me.

**Comment by NZNathan** [comment]
This seems to be due to my generation using an old prefab of the enemies so their public values (specifically their attack range) is wrong. 
Thanks, this should be an easy fix.
